Update/add component print styles
alphagov/feedback pull request #1934
Opened 2024-08-01 15:41 UTC by matthillco

## What
We have 148 components across [GOV.UK](http://gov.uk/) and 13 of them have print styles (see the component auditing for details). This PR updates the print styles for any public-facing components. The changes broadly fall into these categories:

- hiding/removing components that should never be printed
- improving components that already have print styles 
- creating print styles for components that don't already have them

[Trello card](https://trello.com/c/PnEVIZtq/192-review-and-fix-application-component-print-styles)

## Why
People still print a lot of pages from [GOV.UK](http://gov.uk/). And recent discussions have highlighted potential problems, or at least a perception that HTML pages when printed aren't as good as PDFs. We're trying to move away from/discourage the use of PDFs on [GOV.UK](http://gov.uk/), so improving the print experience could help.

2024-08-02 08:31 UTC, andysellick requested changes
@matthillco can you explain what this change is? The PR description appears to be the generic work description copied from the Trello card, but this specific change is hiding a heading when printing. I'd like to know which page this is on and why you're making this change.

2024-08-02 09:07 UTC, matthillco commented
@andysellick

> _The PR description appears to be the generic work description copied from the Trello card_

I've kept the PR description the same in all these apps for consistency. The idea was to explain the PR according to the Trello card, then have each commit be specific about each component change. It worked well in other apps with multiple commits, but here it's just one commit.

> _I'd like to know which page this is on and why you're making this change._

The page is referenced in the tracking spreadsheet which is linked on the Trello card, eg: [https://www.gov.uk/done/transaction-finished](https://www.gov.uk/done/transaction-finished)

This change is simply hiding the grey promotion element when printed as it's basically redundant: the important part of that promotion is the link, which is pointless on a printout. We've used the same logic for hiding other elements in other apps too.

There's also an argument for hiding the Related Content as that's redundant when printed too, however I didn't want to change that here as it might have cascading consequences for other pages.

![image](https://github.com/user-attachments/assets/b5191212-257d-4220-bbad-ed00bc221f7b)

2024-08-02 09:49 UTC, andysellick commented
@matthillco great, thank you for that clear description. Please make that the PR description, and update the PR title accordingly.

2024-08-02 09:51 UTC, andysellick commented
@matthillco please remember that we use github as a history of our changes. Linking to relevant trello cards is useful, but only for background information, as these boards may not be accessible by others or exist forever. A PR description and commit messages should fully encapsulate everything someone needs to know in order to review the change being made.

2024-08-05 14:03 UTC, matthillco commented
> @matthillco great, thank you for that clear description. Please make that the PR description, and update the PR title accordingly.

@andysellick I've updated the title and description as requested.

2024-08-05 14:43 UTC, andysellick approved these changes
Thanks @matthillco

2024-08-05 14:46 UTC, merged